# Generated by Django 3.2.18 on 2025-06-05 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL标识')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_covers/%Y/%m/', verbose_name='封面图片')),
                ('summary', models.TextField(max_length=300, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(default='cuo', max_length=100, verbose_name='作者')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章列表',
                'ordering': ['-pub_date'],
            },
        ),
    ]
