# Generated by Django 3.2.18 on 2025-06-06 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('device_info', models.CharField(default='Android/Chrome', max_length=100, verbose_name='设备信息')),
                ('region', models.CharField(default='湖北', max_length=50, verbose_name='地区')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已退回')], default='pending', max_length=20, verbose_name='状态')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='管理员回复')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
