# Generated by Django 3.2.18 on 2025-06-06 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(default='武软墙', max_length=50, verbose_name='作者')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '生活日记',
                'verbose_name_plural': '生活日记',
            },
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diary_images/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='图片说明')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diary.lifediary')),
            ],
            options={
                'verbose_name': '日记图片',
                'verbose_name_plural': '日记图片',
            },
        ),
        migrations.CreateModel(
            name='DiaryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='diary.lifediary')),
            ],
            options={
                'verbose_name': '日记评论',
                'verbose_name_plural': '日记评论',
            },
        ),
    ]
