# Generated by Django 3.2.18 on 2025-06-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='category',
            field=models.CharField(choices=[('tech', '技术博客'), ('gaming', '游戏社区'), ('friends', '亲朋好友'), ('other', '其他')], default='tech', max_length=20, verbose_name='分类'),
        ),
    ]
